### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by SilasK** [chris-rands/profiles_from_protein_families#1]
Hey @chris-rands,

Could you add me as a contributor so I can directly push to your repo?  

I suggest to try to conform to the guide for [snakemake-workflows project](https://github.com/snakemake-workflows/cookiecutter-snakemake-workflow/tree/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D), what do you think?

**Comment by chris-rands** [comment]
Sure, I just added you as a collaborator, you should receive an invite?

**Comment by chris-rands** [comment]
It worked
